# Generated by Django 3.2.7 on 2021-09-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_currentorder_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentorder',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('Dispatch', 'Dispatch'), ('Shipment', 'Shipment'), ('Arrives at', 'Arrives at'), ('Complete', 'Complete')], default='OrderConfirm', max_length=100, null=True),
        ),
    ]
