# Generated by Django 3.2.7 on 2021-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productincart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
